/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mxcatv
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public String usuario;
    public Principal(String usuario) {
        this.usuario=usuario;
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        if(usuario.equals("admin")){
            menuEmpleado.setVisible(true);
            menuEmpleado.setEnabled(true);
            menuempleadon.setEnabled(false);
            menuempleadon.setVisible(false);
        }
        else{
            menuEmpleado.setVisible(false);
            menuEmpleado.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenuItem();
        menuempleadon = new javax.swing.JMenuItem();
        menuitempro = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout dkprincipalLayout = new javax.swing.GroupLayout(dkprincipal);
        dkprincipal.setLayout(dkprincipalLayout);
        dkprincipalLayout.setHorizontalGroup(
            dkprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        dkprincipalLayout.setVerticalGroup(
            dkprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jMenu1.setText("Registros");

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCliente);

        menuEmpleado.setText("Empleado Administrador");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEmpleado);

        menuempleadon.setText("Empleado");
        menuempleadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuempleadonActionPerformed(evt);
            }
        });
        jMenu1.add(menuempleadon);

        menuitempro.setText("Productos");
        menuitempro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemproActionPerformed(evt);
            }
        });
        jMenu1.add(menuitempro);

        jMenuBar1.add(jMenu1);

        menuSalir.setText("Salir");
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkprincipal)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        ManteCliente objmtcliente=new ManteCliente();
        dkprincipal.add(objmtcliente);
        objmtcliente.setVisible(true);
        
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
        ManteEmpleado objmtempleado=new ManteEmpleado();
        dkprincipal.add(objmtempleado);
        objmtempleado.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuempleadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuempleadonActionPerformed
        // TODO add your handling code here
        ManteEmpleadon objempleadon=new ManteEmpleadon(usuario);
        dkprincipal.add(objempleadon);
        objempleadon.setVisible(true);

    }//GEN-LAST:event_menuempleadonActionPerformed

    private void menuitemproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemproActionPerformed
        // TODO add your handling code here:
        ManteProdu objmantepro= new ManteProdu();
        dkprincipal.add(objmantepro);
        objmantepro.setVisible(true);
    }//GEN-LAST:event_menuitemproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dkprincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem menuCliente;
    public javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuempleadon;
    private javax.swing.JMenuItem menuitempro;
    // End of variables declaration//GEN-END:variables
}
